app:
  client:
    git-hub:
      base-url: https://api.github.com
      token: ${GITHUB_TOKEN}
    stack-overflow:
      base-url: https://api.stackexchange.com/2.3

  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 30s

  database-access-type: jpa

spring:
  application:
    name: scrapper
  config:
    import: optional:file:.env[.properties]
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  jackson:
    deserialization:
      READ_UNKNOWN_ENUM_VALUES_USING_DEFAULT_VALUE: true

  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

  liquibase:
    enabled: false

server:
  port: 8083

springdoc:
  swagger-ui:
    path: /swagger-ui

logging:
  config: classpath:log4j2-plain.xml
