app:
  telegram-token: ${TELEGRAM_TOKEN}
  scrapper-url: http://127.0.0.1:8080

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC
  config:
    import: optional:file:.env[.properties]

server:
  port: 8090

springdoc:
  swagger-ui:
    path: /swagger-ui

logging:
  config: classpath:log4j2-plain.xml
